//
// Generated file, do not edit! Created by nedtool 5.0 from AppMessage.msg.
//

#ifndef __WSL_CSMA_APPMESSAGE_M_H
#define __WSL_CSMA_APPMESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace wsl_csma {

/**
 * Class generated from <tt>AppMessage.msg:21</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet AppMessage
 * {
 *     // simulation time at which the message has been generated
 *     int timeStamp;
 * 
 *     // the node identification of the TransmitterNode
 *     int senderId;
 * 
 *     // the current value of the seqno variable
 *     // the seqno should get increased afterward
 *     int sequenceNumber;
 * 
 *     // the total message size in bytes, to be taken from hte messageSize module parameter
 *     int msgSize;
 * }
 * </pre>
 */
class AppMessage : public ::omnetpp::cPacket
{
  protected:
    int timeStamp;
    int senderId;
    int sequenceNumber;
    int msgSize;

  private:
    void copy(const AppMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AppMessage&);

  public:
    AppMessage(const char *name=nullptr, int kind=0);
    AppMessage(const AppMessage& other);
    virtual ~AppMessage();
    AppMessage& operator=(const AppMessage& other);
    virtual AppMessage *dup() const {return new AppMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual int getTimeStamp() const;
    virtual void setTimeStamp(int timeStamp);
    virtual int getSenderId() const;
    virtual void setSenderId(int senderId);
    virtual int getSequenceNumber() const;
    virtual void setSequenceNumber(int sequenceNumber);
    virtual int getMsgSize() const;
    virtual void setMsgSize(int msgSize);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AppMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AppMessage& obj) {obj.parsimUnpack(b);}

} // namespace wsl_csma

#endif // ifndef __WSL_CSMA_APPMESSAGE_M_H

